spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: es01:9200
      cluster-name: es-docker-cluster
  elasticsearch:
    rest:
      uris: es01:9200

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: prometheus
    health:
      show-details: always
  metrics:
    tag:
      application: kotlin-blog