FROM adoptopenjdk/openjdk11:jre-11.0.4_11
EXPOSE 8080
ADD /build/libs/kotlin-backend-0.0.1-SNAPSHOT.jar kotlin-backend-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=prod",  "kotlin-backend-0.0.1-SNAPSHOT.jar"]